'use strict';
(() => {
  const $ = (s) => document.querySelector(s);
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path) { const r = await fetch('/api' + path); const t = await r.text(); let d; try { d = JSON.parse(t); } catch { d = { text:t }; } if (!r.ok) throw new Error(d.error || 'HTTP '+r.status); return d; }
  function kv(k,v){return '<div class="statline"><span>'+esc(k)+'</span><b>'+esc(v)+'</b></div>';}
  function table(rows, cols){return '<table class="table"><thead><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(typeof c[1]==='function'?c[1](r):r[c[1]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
  async function renderAddress(){ const addr = new URLSearchParams(location.search).get('address') || ''; $('#addrInput') && ($('#addrInput').value=addr); if(!addr){$('#result').innerHTML='<p class="muted">Paste an address to load balance, UTXOs, history, and CSV export.</p>'; return;} $('#result').innerHTML='<p class="muted">Loading address…</p>'; try{ const d=await api('/explorer/address/'+encodeURIComponent(addr)); const b=d.balance||{}; const profile=d.profile||{}; const utxos=d.utxos||[]; const history=d.history||[]; $('#result').innerHTML='<div class="pro-grid"><section class="pro-panel"><h2>Balance</h2>'+kv('Confirmed NET',profile.total||b.total||'0')+kv('Spendable',b.spendable||b.balance_net?.spendable||'0')+kv('UTXOs',utxos.length)+kv('Activity',profile.activity_count||history.length)+'</section><section class="pro-panel"><h2>Exports + Watch</h2><div class="actions"><a href="/api/explorer/address/'+encodeURIComponent(addr)+'/csv">CSV export</a><a href="/api/explorer/watchlist?address='+encodeURIComponent(addr)+'">Watchlist API</a><button id="copyAddr">Copy address</button></div></section></div><section class="pro-panel"><h2>UTXOs</h2>'+table(utxos.slice(0,60), [['Outpoint',u=>(u.txid||u.txid_hex||'')+':'+(u.vout??u.index??0)],['NET',u=>((u.amount||u.amount_sats||0)/1e8).toFixed(8)],['Height','height']])+'</section><section class="pro-panel"><h2>Activity</h2>'+table(history.slice(0,80), [['Tx',h=>h.short_txid||h.txid],['Height','height'],['Confirmations','confirmations'],['Mempool',h=>h.mempool?'yes':'no']])+'</section>'; $('#copyAddr')?.addEventListener('click',()=>navigator.clipboard?.writeText(addr)); }catch(e){$('#result').innerHTML='<p class="warn">Address lookup unavailable: '+esc(e.message)+'</p>';}}
  async function renderTx(){ const txid=new URLSearchParams(location.search).get('txid')||''; $('#txInput') && ($('#txInput').value=txid); if(!txid){$('#result').innerHTML='<p class="muted">Paste a txid to inspect transaction status and raw details.</p>'; return;} try{ const d=await api('/explorer/tx/'+encodeURIComponent(txid)); $('#result').innerHTML='<section class="pro-panel"><h2>Transaction</h2>'+kv('txid',d.txid||txid)+kv('confirmations',d.confirmations??'pending')+kv('block',d.block_hash||d.block_height||'mempool')+'<pre class="mono">'+esc(JSON.stringify(d,null,2))+'</pre></section>'; }catch(e){$('#result').innerHTML='<p class="warn">Transaction lookup unavailable: '+esc(e.message)+'</p>';}}
  async function renderBlock(){ const id=new URLSearchParams(location.search).get('block')||''; $('#blockInput') && ($('#blockInput').value=id); if(!id){$('#result').innerHTML='<p class="muted">Paste a height or hash to inspect block details.</p>'; return;} try{ const d=await api('/explorer/block/'+encodeURIComponent(id)); $('#result').innerHTML='<section class="pro-panel"><h2>Block</h2>'+kv('height',d.height??id)+kv('hash',d.hash||d.block_hash||'—')+kv('transactions',(d.txs||d.transactions||[]).length)+'<pre class="mono">'+esc(JSON.stringify(d,null,2))+'</pre></section>'; }catch(e){$('#result').innerHTML='<p class="warn">Block lookup unavailable: '+esc(e.message)+'</p>';}}
  async function renderMempool(){ try{ const d=await api('/explorer/mempool'); const txs=d.transactions||d.txs||[]; $('#result').innerHTML='<div class="pro-grid"><section class="pro-panel"><h2>Mempool</h2>'+kv('Transactions',txs.length||d.count||0)+kv('Min fee rate',d.min_fee_rate||'policy')+kv('Relay',d.relay||'enabled')+'</section><section class="pro-panel"><h2>Actions</h2><div class="actions"><a href="/api/mempool">Raw API</a><a href="index.html#/mempool">Classic view</a></div></section></div><section class="pro-panel"><h2>Pending transactions</h2>'+table(txs.slice(0,100), [['txid',t=>t.txid||t.id],['fee',t=>t.fee_sats||t.fee||0],['age',t=>t.age_seconds||'—']])+'</section>'; }catch(e){$('#result').innerHTML='<p class="warn">Mempool unavailable: '+esc(e.message)+'</p>';}}
  function wireForms(){ document.querySelectorAll('[data-go]').forEach(f=>f.addEventListener('submit',ev=>{ev.preventDefault(); const input=f.querySelector('input'); location.href=f.dataset.go+'?'+f.dataset.param+'='+encodeURIComponent(input.value.trim());})); }
  const page=document.body.dataset.explorerPage; wireForms(); if(page==='address') renderAddress(); if(page==='tx') renderTx(); if(page==='block') renderBlock(); if(page==='mempool') renderMempool();
})();
