'use strict';
(() => {
  const $ = (s) => document.querySelector(s);
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path, options){const r=await fetch('/api'+path, options);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={text:t}}; if(!r.ok) throw new Error(d.error||'HTTP '+r.status); return d;}
  function table(rows, cols){rows=rows||[]; if(!rows.length) return '<p class="muted">No rows yet.</p>'; return '<table class="mini-table"><thead><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(typeof c[1]==='function'?c[1](r):r[c[1]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
  function cents(v){const n=Number(v); if(Number.isFinite(n)) return Math.round(n*100)+'¢'; return esc(v||'—');}
  async function loadMarkets(){try{return (await api('/markets')).markets||[]}catch{return []}}
  function marketId(markets){return new URLSearchParams(location.search).get('market') || markets[0]?.market_id || 'demo';}
  async function renderTrade(){
    const markets=await loadMarkets(); const id=marketId(markets); const market=markets.find(m=>m.market_id===id)||markets[0]||{market_id:id,question:'Sample YES/NO market',outcomes:['YES','NO']};
    let book={}, ticker={}, candles={};
    try{book=await api('/markets/'+encodeURIComponent(id)+'/orderbook')}catch{}
    try{ticker=await api('/markets/'+encodeURIComponent(id)+'/ticker')}catch{}
    try{candles=await api('/markets/'+encodeURIComponent(id)+'/candles?limit=24')}catch{}
    const bids=(book.bids||book.yes_bids||[]).slice(0,12); const asks=(book.asks||book.yes_asks||[]).slice(0,12);
    $('#content').innerHTML='<div class="trader-shell"><section class="trade-card"><h2>'+esc(market.question||market.title||id)+'</h2><div class="metric-row"><span>Mid '+esc(ticker.midpoint_probability??ticker.midpoint??'—')+'</span><span>Spread '+esc(ticker.spread??'—')+'</span><span>Trades '+esc(ticker.trade_count??'—')+'</span></div><div class="chart-placeholder">Live probability history · '+esc((candles.candles||[]).length)+' buckets</div><div class="ladder"><div><h3>YES bids</h3>'+table(bids, [['Price',x=>cents(x.price)],['Size',x=>x.size||x.quantity||0]])+'</div><div><h3>YES asks</h3>'+table(asks, [['Price',x=>cents(x.price)],['Size',x=>x.size||x.quantity||0]])+'</div></div></section><aside class="trade-card"><h2>Order ticket</h2><label>Outcome</label><select id="orderOutcome"><option>YES</option><option>NO</option></select><label>Side</label><select id="orderSide"><option value="buy">Buy</option><option value="sell">Sell</option></select><div class="row"><div><label>Price</label><input id="orderPrice" value="0.50"></div><div><label>Shares</label><input id="orderQty" value="10"></div></div><button id="reviewOrder">Review order</button><p id="orderMsg" class="muted">Live trading uses signed envelopes. Review builds the exact payload.</p></aside></div>';
    $('#reviewOrder')?.addEventListener('click',()=>{const payload={market_id:id,outcome:$('#orderOutcome').value,side:$('#orderSide').value,price:$('#orderPrice').value,quantity:$('#orderQty').value,time_in_force:'GTC'}; $('#orderMsg').innerHTML='Payload ready for wallet signature:<pre class="mono">'+esc(JSON.stringify(payload,null,2))+'</pre>';});
  }
  async function renderPortfolio(){ const trader=new URLSearchParams(location.search).get('trader')||'demo:trader'; let p={}; try{p=await api('/markets/portfolio?trader='+encodeURIComponent(trader))}catch{} $('#content').innerHTML='<section class="trade-card"><h2>Portfolio</h2>'+table(p.positions||p.markets||[], [['Market',x=>x.market_id||x.market||'—'],['Outcome',x=>x.outcome||'—'],['Shares',x=>x.quantity||x.shares||0],['Avg',x=>x.average_entry||x.avg||'—'],['PnL',x=>x.unrealized_pnl||x.pnl||'—']])+'</section><section class="trade-card"><h2>Open orders</h2>'+table(p.open_orders||[], [['Market','market_id'],['Side','side'],['Price',x=>cents(x.price)],['Shares',x=>x.quantity||0]])+'</section>';}
  async function renderDisputes(){ const markets=await loadMarkets(); const id=marketId(markets); let dossier={}, surv={}; try{dossier=await api('/markets/'+encodeURIComponent(id)+'/oracles')}catch{} try{surv=await api('/markets/'+encodeURIComponent(id)+'/surveillance')}catch{} $('#content').innerHTML='<section class="trade-card"><h2>Dispute + evidence panel</h2><p class="muted">Oracle evidence, dispute comments, and surveillance warnings for '+esc(id)+'.</p>'+table(dossier.evidence||[], [['Source',x=>x.source_type||x.type||'evidence'],['Title',x=>x.title||x.url||'—'],['Hash',x=>(x.hash||x.evidence_hash||'').slice(0,16)]])+'<h3>Surveillance</h3><pre class="mono">'+esc(JSON.stringify(surv,null,2))+'</pre></section>';}
  async function renderSettlement(){ const markets=await loadMarkets(); const id=marketId(markets); let r={}; try{r=await api('/markets/'+encodeURIComponent(id)+'/reconciliation')}catch{} $('#content').innerHTML='<section class="trade-card"><h2>Settlement report</h2><p class="muted">Reconciliation checks for winning payouts, losing collateral, dust, and resolved market immutability.</p>'+table(r.checks||r.items||[], [['Check',x=>x.check||x.name||'—'],['Status',x=>x.status||'review'],['Detail',x=>x.detail||'']])+'<pre class="mono">'+esc(JSON.stringify(r,null,2))+'</pre></section>';}
  const page=document.body.dataset.marketPage; if(page==='portfolio')renderPortfolio(); else if(page==='disputes')renderDisputes(); else if(page==='settlement')renderSettlement(); else renderTrade();
})();
